"""document and chunk models

Revision ID: 5d2a74aeea57
Revises: 5ec48671c2ee
Create Date: 2026-06-26 13:43:24.282483

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '5d2a74aeea57'
down_revision: Union[str, Sequence[str], None] = '5ec48671c2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('minio_key', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'ERROR', name='status_enum'), server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (status = 'ERROR' AND error_message IS NOT NULL)\n            OR\n            (status <> 'ERROR' AND error_message IS NULL)\n            ", name='ck_documents_error_message_matches_status'),
    sa.CheckConstraint("\n            (status = 'INDEXED' AND indexed_at IS NOT NULL)\n            OR\n            (status <> 'INDEXED' AND indexed_at IS NULL)\n            ", name='ck_documents_indexed_at_matches_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum'),
    sa.UniqueConstraint('minio_key')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_index', 'document_id', name='uq_chunk_index_document_id')
    )
    op.create_index('hnsw_ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('hnsw_ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###

    ENUM(name="status_enum").drop(op.get_bind(), checkfirst=False)
